### ISSUE TITLE
Picture size for .svg files

### ISSUE THREAD

**Issue by madeindjs** [alangrafu/timeknots#7]
`.svg` file are correctly appear as picture but we can't specify the size and it bent the picture

![screenshot](https://cloud.githubusercontent.com/assets/11815139/18907003/293acb12-856a-11e6-961b-09829f625e40.png)

I corrected it with css:

``` css
#timeline1 img{height: 100px; height: 100px; }
```

But it shoul be great to have a option to specify it
